language:
  - c
  - cpp

os: linux
compiler: gcc  

sudo: required 
dist: trusty

env:
  - BUILD=x86_64-linux-gnu_release
    CXXFLAGS=-m64 CFLAGS=-m64 LDFLAGS=-m64
    DEBUG_MODE=OFF
  - BUILD=x86_64-linux-gnu_debug
    CXXFLAGS=-m64 CFLAGS=-m64 LDFLAGS=-m64
    DEBUG_MODE=ON
  - BUILD=i686-linux-gnu_release
    CXXFLAGS=-m32 CFLAGS=-m32
    DEBUG_MODE=OFF
  - BUILD=i686-linux-gnu_debug
    CXXFLAGS=-m32 CFLAGS=-m32
    DEBUG_MODE=ON

install:
   - sudo apt-get install gcc-multilib g++-multilib

before_script:
  - "mkdir build"
  - "cd build"
  - cmake -DBUILD_TOOL_TESTS=ON -DDEBUG=$DEBUG_MODE ../drltrace_src/

script: 
  - "make"
  - "ctest -VV"
